### ISSUE TITLE
How long will be installation ?

### ISSUE THREAD

**Issue by Chertoganov** [cosmic-cortex/fastAPI-ML-quickstart#3]
How long will be installation ?

**Comment by Chertoganov** [comment]
Installing collected packages: starlette, pydantic, fastapi, uvloop, httptools, h11, click, websockets, uvicorn, numpy, scipy, threadpoolctl, joblib, scikit-learn, sklearn, pytz, python-dateutil, pandas, python-multipart, more-itertools, zipp, importlib-metadata, pluggy, wcwidth, py, attrs, pyparsing, packaging, pytest, chardet, idna, certifi, urllib3, requests
Successfully installed attrs-19.3.0 certifi-2020.4.5.1 chardet-3.0.4 click-7.1.2 fastapi-0.54.2 h11-0.9.0 httptools-0.1.1 idna-2.9 importlib-metadata-1.6.0 joblib-0.15.1 more-itertools-8.3.0 numpy-1.18.4 packaging-20.3 pandas-1.0.3 pluggy-0.13.1 py-1.8.1 pydantic-1.5.1 pyparsing-2.4.7 pytest-5.4.2 python-dateutil-2.8.1 python-multipart-0.0.5 pytz-2020.1 requests-2.23.0 scikit-learn-0.23.0 scipy-1.4.1 sklearn-0.0 starlette-0.13.2 threadpoolctl-2.0.0 urllib3-1.25.9 uvicorn-0.11.5 uvloop-0.14.0 wcwidth-0.1.9 websockets-8.1 zipp-3.1.0

**Comment by Chertoganov** [comment]
and after this nothing just waiting...

**Comment by Chertoganov** [comment]
Successfully installed attrs-19.3.0 certifi-2020.4.5.1 chardet-3.0.4 click-7.1.2 fastapi-0.54.2 h11-0.9.0 httptools-0.1.1 idna-2.9 importlib-metadata-1.6.0 joblib-0.15.1 more-itertools-8.3.0 numpy-1.18.4 packaging-20.3 pandas-1.0.3 pluggy-0.13.1 py-1.8.1 pydantic-1.5.1 pyparsing-2.4.7 pytest-5.4.2 python-dateutil-2.8.1 python-multipart-0.0.5 pytz-2020.1 requests-2.23.0 scikit-learn-0.23.0 scipy-1.4.1 sklearn-0.0 starlette-0.13.2 threadpoolctl-2.0.0 urllib3-1.25.9 uvicorn-0.11.5 uvloop-0.14.0 wcwidth-0.1.9 websockets-8.1 zipp-3.1.0
Traceback (most recent call last):
  File "http\client.py", line 546, in _get_chunk_left
  File "http\client.py", line 513, in _read_next_chunk_size
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "http\client.py", line 578, in _readinto_chunked
  File "http\client.py", line 548, in _get_chunk_left
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\urllib3\response.py", line 362, in _error_catcher
  File "site-packages\urllib3\response.py", line 444, in read
  File "http\client.py", line 449, in read
  File "http\client.py", line 483, in readinto
  File "http\client.py", line 594, in _readinto_chunked
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1085, in up
  File "compose\cli\main.py", line 1081, in up
  File "compose\project.py", line 527, in up
  File "compose\service.py", line 360, in ensure_image_exists
  File "compose\service.py", line 1088, in build
  File "compose\progress_stream.py", line 25, in stream_output
  File "compose\utils.py", line 61, in split_buffer
  File "compose\utils.py", line 37, in stream_as_text
  File "site-packages\docker\api\client.py", line 345, in _stream_helper
  File "site-packages\urllib3\response.py", line 461, in read
  File "contextlib.py", line 99, in __exit__
  File "site-packages\urllib3\response.py", line 380, in _error_catcher
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
[26580] Failed to execute script docker-compose

**Comment by cosmic-cortex** [comment]
Actually, you don't install, you just build the image and launch the Docker container. I am not sure what this error is, did you get it when executing `docker-compose up`?
